with System; use System;
with SAM.SERCOM.SPI; use SAM.SERCOM.SPI;
with SAM.SERCOM; use SAM.SERCOM;
with SAM.Port; use SAM.Port;
with SAM.ADC; use SAM.ADC;

--  Generated by a script from an "avr tools device file" (atdf)
package SAM.Device is

   -- ADC0 --

   ADC0_Internal : aliased SAM.ADC.ADC_Internal
     with Import, Address => System'To_Address (16#43001C00#);

   ADC0 : aliased SAM.ADC.ADC_Device (ADC0_Internal'Access);

   -- ADC1 --

   ADC1_Internal : aliased SAM.ADC.ADC_Internal
     with Import, Address => System'To_Address (16#43002000#);

   ADC1 : aliased SAM.ADC.ADC_Device (ADC1_Internal'Access);

   -- PORTA --

   PORTA_Internal : aliased Port_Internal
     with Import, Address => System'To_Address (16#41008000# + 16#000#);
   PORTA : aliased Port_Controller (PORTA_Internal'Access);

   PA00 : aliased GPIO_Point (PORTA'Access, 0);
   PA01 : aliased GPIO_Point (PORTA'Access, 1);
   PA02 : aliased GPIO_Point (PORTA'Access, 2);
   PA03 : aliased GPIO_Point (PORTA'Access, 3);
   PA04 : aliased GPIO_Point (PORTA'Access, 4);
   PA05 : aliased GPIO_Point (PORTA'Access, 5);
   PA06 : aliased GPIO_Point (PORTA'Access, 6);
   PA07 : aliased GPIO_Point (PORTA'Access, 7);
   PA08 : aliased GPIO_Point (PORTA'Access, 8);
   PA09 : aliased GPIO_Point (PORTA'Access, 9);
   PA10 : aliased GPIO_Point (PORTA'Access, 10);
   PA11 : aliased GPIO_Point (PORTA'Access, 11);
   PA12 : aliased GPIO_Point (PORTA'Access, 12);
   PA13 : aliased GPIO_Point (PORTA'Access, 13);
   PA14 : aliased GPIO_Point (PORTA'Access, 14);
   PA15 : aliased GPIO_Point (PORTA'Access, 15);
   PA16 : aliased GPIO_Point (PORTA'Access, 16);
   PA17 : aliased GPIO_Point (PORTA'Access, 17);
   PA18 : aliased GPIO_Point (PORTA'Access, 18);
   PA19 : aliased GPIO_Point (PORTA'Access, 19);
   PA20 : aliased GPIO_Point (PORTA'Access, 20);
   PA21 : aliased GPIO_Point (PORTA'Access, 21);
   PA22 : aliased GPIO_Point (PORTA'Access, 22);
   PA23 : aliased GPIO_Point (PORTA'Access, 23);
   PA24 : aliased GPIO_Point (PORTA'Access, 24);
   PA25 : aliased GPIO_Point (PORTA'Access, 25);
   PA26 : aliased GPIO_Point (PORTA'Access, 26);
   PA27 : aliased GPIO_Point (PORTA'Access, 27);
   PA28 : aliased GPIO_Point (PORTA'Access, 28);
   PA29 : aliased GPIO_Point (PORTA'Access, 29);
   PA30 : aliased GPIO_Point (PORTA'Access, 30);
   PA31 : aliased GPIO_Point (PORTA'Access, 31);

   -- PORTB --

   PORTB_Internal : aliased Port_Internal
     with Import, Address => System'To_Address (16#41008000# + 16#080#);
   PORTB : aliased Port_Controller (PORTB_Internal'Access);

   PB00 : aliased GPIO_Point (PORTB'Access, 0);
   PB01 : aliased GPIO_Point (PORTB'Access, 1);
   PB02 : aliased GPIO_Point (PORTB'Access, 2);
   PB03 : aliased GPIO_Point (PORTB'Access, 3);
   PB04 : aliased GPIO_Point (PORTB'Access, 4);
   PB05 : aliased GPIO_Point (PORTB'Access, 5);
   PB06 : aliased GPIO_Point (PORTB'Access, 6);
   PB07 : aliased GPIO_Point (PORTB'Access, 7);
   PB08 : aliased GPIO_Point (PORTB'Access, 8);
   PB09 : aliased GPIO_Point (PORTB'Access, 9);
   PB10 : aliased GPIO_Point (PORTB'Access, 10);
   PB11 : aliased GPIO_Point (PORTB'Access, 11);
   PB12 : aliased GPIO_Point (PORTB'Access, 12);
   PB13 : aliased GPIO_Point (PORTB'Access, 13);
   PB14 : aliased GPIO_Point (PORTB'Access, 14);
   PB15 : aliased GPIO_Point (PORTB'Access, 15);
   PB16 : aliased GPIO_Point (PORTB'Access, 16);
   PB17 : aliased GPIO_Point (PORTB'Access, 17);
   PB18 : aliased GPIO_Point (PORTB'Access, 18);
   PB19 : aliased GPIO_Point (PORTB'Access, 19);
   PB20 : aliased GPIO_Point (PORTB'Access, 20);
   PB21 : aliased GPIO_Point (PORTB'Access, 21);
   PB22 : aliased GPIO_Point (PORTB'Access, 22);
   PB23 : aliased GPIO_Point (PORTB'Access, 23);
   PB24 : aliased GPIO_Point (PORTB'Access, 24);
   PB25 : aliased GPIO_Point (PORTB'Access, 25);
   PB26 : aliased GPIO_Point (PORTB'Access, 26);
   PB27 : aliased GPIO_Point (PORTB'Access, 27);
   PB28 : aliased GPIO_Point (PORTB'Access, 28);
   PB29 : aliased GPIO_Point (PORTB'Access, 29);
   PB30 : aliased GPIO_Point (PORTB'Access, 30);
   PB31 : aliased GPIO_Point (PORTB'Access, 31);

   -- SERCOM0 --

   SERCOM0_Internal : aliased SAM.SERCOM.SERCOM_Internal
     with Import, Address => System'To_Address (16#40003000#);

   SPI0 : aliased SAM.SERCOM.SPI.SPI_Device (SERCOM0_Internal'Access);

   -- SERCOM1 --

   SERCOM1_Internal : aliased SAM.SERCOM.SERCOM_Internal
     with Import, Address => System'To_Address (16#40003400#);

   SPI1 : aliased SAM.SERCOM.SPI.SPI_Device (SERCOM1_Internal'Access);

   -- SERCOM2 --

   SERCOM2_Internal : aliased SAM.SERCOM.SERCOM_Internal
     with Import, Address => System'To_Address (16#41012000#);

   SPI2 : aliased SAM.SERCOM.SPI.SPI_Device (SERCOM2_Internal'Access);

   -- SERCOM3 --

   SERCOM3_Internal : aliased SAM.SERCOM.SERCOM_Internal
     with Import, Address => System'To_Address (16#41014000#);

   SPI3 : aliased SAM.SERCOM.SPI.SPI_Device (SERCOM3_Internal'Access);

   -- SERCOM4 --

   SERCOM4_Internal : aliased SAM.SERCOM.SERCOM_Internal
     with Import, Address => System'To_Address (16#43000000#);

   SPI4 : aliased SAM.SERCOM.SPI.SPI_Device (SERCOM4_Internal'Access);

   -- SERCOM5 --

   SERCOM5_Internal : aliased SAM.SERCOM.SERCOM_Internal
     with Import, Address => System'To_Address (16#43000400#);

   SPI5 : aliased SAM.SERCOM.SPI.SPI_Device (SERCOM5_Internal'Access);

end SAM.Device;
