# Appveyor continuous builder configuration

# Version format, we don't have version number for ADL yet
version: 0.0.{build}

# Setup python for build and test-suite scripts
environment:
  PYTHON: C:\\Python27
  TOOLS_DIR: C:\ADL_tools\
  GNAT_ARM_ELF_INSTALLER: C:\ADL_tools\gnat-gpl-2017-arm-elf-windows-bin.exe
  INSTALL_DIR: C:\Install\

# Cache directories will be preseved from one build to the other
cache:
  - C:\ADL_tools

install:
# Show current dir and its content
- cmd: cd
- cmd: dir

# Create the tool dir if it doesn't exists
- ps: md -f $env:TOOLS_DIR
- ps: md -f $env:INSTALL_DIR

# Show content of tool dir
- cmd: dir %TOOLS_DIR%
- cmd: dir %INSTALL_DIR%

# Download compiler installer if not already in the tool dir
- ps: If (Test-Path $env:GNAT_ARM_ELF_INSTALLER){echo compiler already in cache}Else{(new-object net.webclient).DownloadFile('http://mirrors.cdn.adacore.com/art/591cd401a3f5d779efba822d', $env:GNAT_ARM_ELF_INSTALLER)}

# Show content of tool dir again so we can see if the download was ok
- cmd: dir %TOOLS_DIR%

# Install the compiler
- cmd: cmd /c start /wait %GNAT_ARM_ELF_INSTALLER% /S /D=%INSTALL_DIR%

# Show content of install dir so we can see if install was ok
- cmd: dir %INSTALL_DIR%

# Add compiler to the PATH
- ps: $env:Path += ";" + $env:INSTALL_DIR +"bin"

# Check that we can run the compiler (also display the version)
- ps: arm-eabi-gnatls -v

# Install optional dependencies
- cmd: python scripts/install_dependencies.py

# We don't need a build step
build: off

# Run the test script(s)
test_script:
- cmd: python scripts/build_all_examples.py
