pragma Warnings (Off);
with Interfaces; use Interfaces;
with HAL; use HAL;
pragma Warnings (On);

package SAM is
   pragma Pure;

   --  Peripheral Identifiers
   SUPC_ID         : constant := 0;
   RSTC_ID         : constant := 1;
   RTC_ID          : constant := 2;
   RTT_ID          : constant := 3;
   WDT_ID          : constant := 4;
   PMC_ID          : constant := 5;
   EFC_ID          : constant := 6;
   UART0_ID        : constant := 7;
   UART1_ID        : constant := 8;
   SMC_ID          : constant := 9;
   PIOA_ID         : constant := 10;
   PIOB_ID         : constant := 11;
   PIOC_ID         : constant := 12;
   USART0_ID       : constant := 13;
   USART1_ID       : constant := 14;
   USART2_ID       : constant := 15;
   PIOD_ID         : constant := 16;
   PIOE_ID         : constant := 17;
   HSMCI_ID        : constant := 18;
   TWIHS0_ID       : constant := 19;
   TWIHS1_ID       : constant := 20;
   SPI0_ID         : constant := 21;
   SSC_ID          : constant := 22;
   TC0_CHANNEL0_ID : constant := 23;
   TC0_CHANNEL1_ID : constant := 24;
   TC0_CHANNEL2_ID : constant := 25;
   TC1_CHANNEL0_ID : constant := 26;
   TC1_CHANNEL1_ID : constant := 27;
   TC1_CHANNEL2_ID : constant := 28;
   AFEC0_ID        : constant := 29;
   DACC_ID         : constant := 30;
   PWM0_ID         : constant := 31;
   ICM_ID          : constant := 32;
   ACC_ID          : constant := 33;
   USBHS_ID        : constant := 34;
   MCAN0_INT0_ID   : constant := 35;
   MCAN0_INT1_ID   : constant := 36;
   MCAN1_INT0_ID   : constant := 37;
   MCAN1_INT1_ID   : constant := 38;
   GMAC_ID         : constant := 39;
   AFEC1_ID        : constant := 40;
   TWIHS2_ID       : constant := 41;
   SPI1_ID         : constant := 42;
   QSPI_ID         : constant := 43;
   UART2_ID        : constant := 44;
   UART3_ID        : constant := 45;
   UART4_ID        : constant := 46;
   TC2_CHANNEL0_ID : constant := 47;
   TC2_CHANNEL1_ID : constant := 48;
   TC2_CHANNEL2_ID : constant := 49;
   TC3_CHANNEL0_ID : constant := 50;
   TC3_CHANNEL1_ID : constant := 51;
   TC3_CHANNEL2_ID : constant := 52;
   MLB_0_ID        : constant := 53;
   MLB_1_ID        : constant := 54;

   AES_ID         : constant := 56;
   TRNG_ID        : constant := 57;
   XDMAC_ID       : constant := 58;
   ISI_ID         : constant := 59;
   PWM1_ID        : constant := 60;
   ARM_FPU_ID     : constant := 61;
   SDRAMC_ID      : constant := 62;
   RSWDT_ID       : constant := 63;
   ARM_CCW_ID     : constant := 64;
   ARM_CCF_ID     : constant := 65;
   GMAC_Q1_ID     : constant := 66;
   GMAC_Q2_ID     : constant := 67;
   ARM_IXC_ID     : constant := 68;
   I2SC0_ID       : constant := 69;
   I2SC1_ID       : constant := 70;
   GMAC_Q3_ID     : constant := 71;
   GMAC_Q4_ID     : constant := 72;
   GMAC_Q5_ID     : constant := 73;

end SAM;
