--  This package was generated by the Ada_Drivers_Library project wizard script
package ADL_Config is
   Vendor                         : constant String  := "STMicro";           -- From board definition
   Runtime_Profile                : constant String  := "ravenscar-sfp";     -- From command line
   Device_Name                    : constant String  := "STM32F746NGHx";     -- From board definition
   Device_Family                  : constant String  := "STM32F7";           -- From board definition
   Runtime_Name                   : constant String  := "ravenscar-sfp-stm32f746disco"; -- From default value
   Has_Ravenscar_Full_Runtime     : constant String  := "True";              -- From board definition
   CPU_Core                       : constant String  := "ARM Cortex-M7F";    -- From mcu definition
   Board                          : constant String  := "STM32F746_Discovery"; -- From command line
   Has_ZFP_Runtime                : constant String  := "False";             -- From board definition
   Has_Ravenscar_SFP_Runtime      : constant String  := "True";              -- From board definition
   High_Speed_External_Clock      : constant         := 25000000;            -- From board definition
   Runtime_Name_Suffix            : constant String  := "stm32f746disco";    -- From board definition
   Architecture                   : constant String  := "ARM";               -- From board definition
end ADL_Config;
