--  This package was generated by the Ada_Drivers_Library project wizzard script
package ADL_Config is
   VENDOR                         : constant String  := "SiFive";            -- From board definition
   RUNTIME_PROFILE                : constant String  := "zfp";               -- From command line
   DEVICE_NAME                    : constant String  := "FE310";             -- From board definition
   DEVICE_FAMILY                  : constant String  := "FE3";               -- From board definition
   RUNTIME_NAME                   : constant String  := "zfp-hifive1";       -- From default value
   HAS_RAVENSCAR_FULL_RUNTIME     : constant String  := "False";             -- From board definition
   CPU_CORE                       : constant String  := "RISC-V32";          -- From mcu definition
   BOARD                          : constant String  := "HiFive1";           -- From command line
   HAS_ZFP_RUNTIME                : constant String  := "True";              -- From board definition
   HAS_RAVENSCAR_SFP_RUNTIME      : constant String  := "False";             -- From board definition
   ARCH                           : constant String  := "RISC-V";            -- From board definition
   RUNTIME_NAME_SUFFIX            : constant String  := "hifive1";           -- From board definition
end ADL_Config;
