--  This package was generated by the Ada_Drivers_Library project wizard script
package ADL_Config is
   Board                          : constant String  := "MicroBit";          -- From user input
   Architecture                   : constant String  := "ARM";               -- From board definition
   Vendor                         : constant String  := "Nordic";            -- From board definition
   Device_Family                  : constant String  := "nRF51";             -- From board definition
   Device_Name                    : constant String  := "nRF51822xxAA";      -- From board definition
   CPU_Core                       : constant String  := "ARM Cortex-M0";     -- From mcu definition
   Number_Of_Interrupts           : constant         := 32;                  -- From MCU definition
   Has_ZFP_Runtime                : constant String  := "True";              -- From board definition
   Has_Ravenscar_SFP_Runtime      : constant String  := "False";             -- From board definition
   Has_Ravenscar_Full_Runtime     : constant String  := "False";             -- From board definition
   Runtime_Profile                : constant String  := "zfp";               -- From user input
   Runtime_Name_Suffix            : constant String  := "cortex-m0";         -- From board definition
   Runtime_Name                   : constant String  := "zfp-cortex-m0";     -- From user input
   Use_Startup_Gen                : constant Boolean := True;                -- From user input
   Has_Custom_Memory_Area_1       : constant Boolean := False;               -- From user input
   Boot_Memory                    : constant String  := "flash";             -- From user input
   Max_Path_Length                : constant         := 1024;                -- From user input
   Max_Mount_Points               : constant         := 2;                   -- From user input
   Max_Mount_Name_Length          : constant         := 128;                 -- From user input
end ADL_Config;
