--  Generated by a script from an "avr tools device file" (atdf)
package SAM.Main_Clock is

   -- HPB0 --
   procedure HPB0_On with Inline;
   procedure HPB0_Off with Inline;

   -- HPB1 --
   procedure HPB1_On with Inline;
   procedure HPB1_Off with Inline;

   -- HPB2 --
   procedure HPB2_On with Inline;
   procedure HPB2_Off with Inline;

   -- HPB3 --
   procedure HPB3_On with Inline;
   procedure HPB3_Off with Inline;

   -- DSU --
   procedure DSU_On with Inline;
   procedure DSU_Off with Inline;

   -- HMATRIX --
   procedure HMATRIX_On with Inline;
   procedure HMATRIX_Off with Inline;

   -- NVMCTRL --
   procedure NVMCTRL_On with Inline;
   procedure NVMCTRL_Off with Inline;

   -- HSRAM --
   procedure HSRAM_On with Inline;
   procedure HSRAM_Off with Inline;

   -- CMCC --
   procedure CMCC_On with Inline;
   procedure CMCC_Off with Inline;

   -- DMAC --
   procedure DMAC_On with Inline;
   procedure DMAC_Off with Inline;

   -- USB --
   procedure USB_On with Inline;
   procedure USB_Off with Inline;

   -- BKUPRAM --
   procedure BKUPRAM_On with Inline;
   procedure BKUPRAM_Off with Inline;

   -- PAC --
   procedure PAC_On with Inline;
   procedure PAC_Off with Inline;

   -- QSPI --
   procedure QSPI_On with Inline;
   procedure QSPI_Off with Inline;

   -- SDHC0 --
   procedure SDHC0_On with Inline;
   procedure SDHC0_Off with Inline;

   -- SDHC1 --
   procedure SDHC1_On with Inline;
   procedure SDHC1_Off with Inline;

   -- ICM --
   procedure ICM_On with Inline;
   procedure ICM_Off with Inline;

   -- PUKCC --
   procedure PUKCC_On with Inline;
   procedure PUKCC_Off with Inline;

   -- QSPI_2X --
   procedure QSPI_2X_On with Inline;
   procedure QSPI_2X_Off with Inline;

   -- NVMCTRL_SMEEPROM --
   procedure NVMCTRL_SMEEPROM_On with Inline;
   procedure NVMCTRL_SMEEPROM_Off with Inline;

   -- NVMCTRL_CACHE --
   procedure NVMCTRL_CACHE_On with Inline;
   procedure NVMCTRL_CACHE_Off with Inline;

   -- PM --
   procedure PM_On with Inline;
   procedure PM_Off with Inline;

   -- MCLK --
   procedure MCLK_On with Inline;
   procedure MCLK_Off with Inline;

   -- RSTC --
   procedure RSTC_On with Inline;
   procedure RSTC_Off with Inline;

   -- OSCCTRL --
   procedure OSCCTRL_On with Inline;
   procedure OSCCTRL_Off with Inline;

   -- OSC32KCTRL --
   procedure OSC32KCTRL_On with Inline;
   procedure OSC32KCTRL_Off with Inline;

   -- SUPC --
   procedure SUPC_On with Inline;
   procedure SUPC_Off with Inline;

   -- GCLK --
   procedure GCLK_On with Inline;
   procedure GCLK_Off with Inline;

   -- WDT --
   procedure WDT_On with Inline;
   procedure WDT_Off with Inline;

   -- RTC --
   procedure RTC_On with Inline;
   procedure RTC_Off with Inline;

   -- EIC --
   procedure EIC_On with Inline;
   procedure EIC_Off with Inline;

   -- FREQM --
   procedure FREQM_On with Inline;
   procedure FREQM_Off with Inline;

   -- SERCOM0 --
   procedure SERCOM0_On with Inline;
   procedure SERCOM0_Off with Inline;

   -- SERCOM1 --
   procedure SERCOM1_On with Inline;
   procedure SERCOM1_Off with Inline;

   -- TC0 --
   procedure TC0_On with Inline;
   procedure TC0_Off with Inline;

   -- TC1 --
   procedure TC1_On with Inline;
   procedure TC1_Off with Inline;

   -- PORT --
   procedure PORT_On with Inline;
   procedure PORT_Off with Inline;

   -- EVSYS --
   procedure EVSYS_On with Inline;
   procedure EVSYS_Off with Inline;

   -- SERCOM2 --
   procedure SERCOM2_On with Inline;
   procedure SERCOM2_Off with Inline;

   -- SERCOM3 --
   procedure SERCOM3_On with Inline;
   procedure SERCOM3_Off with Inline;

   -- TCC0 --
   procedure TCC0_On with Inline;
   procedure TCC0_Off with Inline;

   -- TCC1 --
   procedure TCC1_On with Inline;
   procedure TCC1_Off with Inline;

   -- TC2 --
   procedure TC2_On with Inline;
   procedure TC2_Off with Inline;

   -- TC3 --
   procedure TC3_On with Inline;
   procedure TC3_Off with Inline;

   -- TAL --
   procedure TAL_On with Inline;
   procedure TAL_Off with Inline;

   -- RAMECC --
   procedure RAMECC_On with Inline;
   procedure RAMECC_Off with Inline;

   -- TCC2 --
   procedure TCC2_On with Inline;
   procedure TCC2_Off with Inline;

   -- TCC3 --
   procedure TCC3_On with Inline;
   procedure TCC3_Off with Inline;

   -- TC4 --
   procedure TC4_On with Inline;
   procedure TC4_Off with Inline;

   -- TC5 --
   procedure TC5_On with Inline;
   procedure TC5_Off with Inline;

   -- PDEC --
   procedure PDEC_On with Inline;
   procedure PDEC_Off with Inline;

   -- AC --
   procedure AC_On with Inline;
   procedure AC_Off with Inline;

   -- AES --
   procedure AES_On with Inline;
   procedure AES_Off with Inline;

   -- TRNG --
   procedure TRNG_On with Inline;
   procedure TRNG_Off with Inline;

   -- CCL --
   procedure CCL_On with Inline;
   procedure CCL_Off with Inline;

   -- SERCOM4 --
   procedure SERCOM4_On with Inline;
   procedure SERCOM4_Off with Inline;

   -- SERCOM5 --
   procedure SERCOM5_On with Inline;
   procedure SERCOM5_Off with Inline;

   -- SERCOM6 --
   procedure SERCOM6_On with Inline;
   procedure SERCOM6_Off with Inline;

   -- SERCOM7 --
   procedure SERCOM7_On with Inline;
   procedure SERCOM7_Off with Inline;

   -- TCC4 --
   procedure TCC4_On with Inline;
   procedure TCC4_Off with Inline;

   -- TC6 --
   procedure TC6_On with Inline;
   procedure TC6_Off with Inline;

   -- TC7 --
   procedure TC7_On with Inline;
   procedure TC7_Off with Inline;

   -- ADC0 --
   procedure ADC0_On with Inline;
   procedure ADC0_Off with Inline;

   -- ADC1 --
   procedure ADC1_On with Inline;
   procedure ADC1_Off with Inline;

   -- DAC --
   procedure DAC_On with Inline;
   procedure DAC_Off with Inline;

   -- I2S --
   procedure I2S_On with Inline;
   procedure I2S_Off with Inline;

   -- PCC --
   procedure PCC_On with Inline;
   procedure PCC_Off with Inline;
end SAM.Main_Clock;
