--  This package was generated by the Ada_Drivers_Library project wizzard script
package ADL_Config is
   HAS_RAVENSCAR_SFP_RUNTIME      : constant String  := "False";             -- From default value
   HAS_RAVENSCAR_FULL_RUNTIME     : constant String  := "False";             -- From default value
   ARCH                           : constant String  := "Native";            -- From board definition
   BOARD                          : constant String  := "Native";            -- From command line
   HAS_ZFP_RUNTIME                : constant String  := "False";             -- From default value
end ADL_Config;
