--  This package was generated by the Ada_Drivers_Library project wizzard script
package ADL_Config is
   VENDOR                         : constant String  := "Nordic";            -- From board definition
   RUNTIME_PROFILE                : constant String  := "zfp";               -- From command line
   DEVICE_NAME                    : constant String  := "nRF51822xxAA";      -- From board definition
   DEVICE_FAMILY                  : constant String  := "nRF51";             -- From board definition
   RUNTIME_NAME                   : constant String  := "zfp-nrf51";         -- From default value
   HAS_RAVENSCAR_FULL_RUNTIME     : constant String  := "False";             -- From board definition
   CPU_CORE                       : constant String  := "ARM Cortex-M0";     -- From mcu definition
   BOARD                          : constant String  := "MicroBit";          -- From command line
   HAS_ZFP_RUNTIME                : constant String  := "True";              -- From board definition
   HAS_RAVENSCAR_SFP_RUNTIME      : constant String  := "False";             -- From board definition
   ARCH                           : constant String  := "ARM";               -- From board definition
   RUNTIME_NAME_SUFFIX            : constant String  := "nrf51";             -- From board definition
end ADL_Config;
