--  This package was generated by the Ada_Drivers_Library project wizard script
package ADL_Config is
   Has_Ravenscar_SFP_Runtime      : constant String  := "False";             -- From default value
   Has_ZFP_Runtime                : constant String  := "False";             -- From default value
   Has_Ravenscar_Full_Runtime     : constant String  := "False";             -- From default value
   Board                          : constant String  := "Native";            -- From command line
   Architecture                   : constant String  := "Native";            -- From board definition
end ADL_Config;
