--  This package was generated by the Ada_Drivers_Library project wizard script
package ADL_Config is
   Max_Mount_Points               : constant         := 2;                   -- From default value
   Max_Mount_Name_Length          : constant         := 128;                 -- From default value
   Has_Ravenscar_Full_Runtime     : constant String  := "False";             -- From default value
   Board                          : constant String  := "Native";            -- From command line
   Has_ZFP_Runtime                : constant String  := "False";             -- From default value
   Has_Ravenscar_SFP_Runtime      : constant String  := "False";             -- From default value
   Use_Startup_Gen                : constant Boolean := False;               -- From command line
   Max_Path_Length                : constant         := 1024;                -- From default value
   Architecture                   : constant String  := "Native";            -- From board definition
end ADL_Config;
