with SAM_SVD; use SAM_SVD;

with SAM.GPIO; use SAM.GPIO;
with SAM.SPI; use SAM.SPI;

package SAM.Device is
   pragma Elaborate_Body;

   Unknown_Device : exception;
   --  Raised by the routines below for a device passed as an actual parameter
   --  when that device is not present on the given hardware instance.

   GPIO_A : aliased GPIO_Port with Import, Volatile, Address => PIOA_Base;
   GPIO_B : aliased GPIO_Port with Import, Volatile, Address => PIOB_Base;
   GPIO_C : aliased GPIO_Port with Import, Volatile, Address => PIOC_Base;
   GPIO_D : aliased GPIO_Port with Import, Volatile, Address => PIOD_Base;
   GPIO_E : aliased GPIO_Port with Import, Volatile, Address => PIOE_Base;

   PA0    : aliased GPIO_Point := (GPIO_A'Access, 0);
   PA1    : aliased GPIO_Point := (GPIO_A'Access, 1);
   PA2    : aliased GPIO_Point := (GPIO_A'Access, 2);
   PA3    : aliased GPIO_Point := (GPIO_A'Access, 3);
   PA4    : aliased GPIO_Point := (GPIO_A'Access, 4);
   PA5    : aliased GPIO_Point := (GPIO_A'Access, 5);
   PA6    : aliased GPIO_Point := (GPIO_A'Access, 6);
   PA7    : aliased GPIO_Point := (GPIO_A'Access, 7);
   PA8    : aliased GPIO_Point := (GPIO_A'Access, 8);
   PA9    : aliased GPIO_Point := (GPIO_A'Access, 9);
   PA10   : aliased GPIO_Point := (GPIO_A'Access, 10);
   PA11   : aliased GPIO_Point := (GPIO_A'Access, 11);
   PA12   : aliased GPIO_Point := (GPIO_A'Access, 12);
   PA13   : aliased GPIO_Point := (GPIO_A'Access, 13);
   PA14   : aliased GPIO_Point := (GPIO_A'Access, 14);
   PA15   : aliased GPIO_Point := (GPIO_A'Access, 15);
   PA16   : aliased GPIO_Point := (GPIO_A'Access, 16);
   PA17   : aliased GPIO_Point := (GPIO_A'Access, 17);
   PA18   : aliased GPIO_Point := (GPIO_A'Access, 18);
   PA19   : aliased GPIO_Point := (GPIO_A'Access, 19);
   PA20   : aliased GPIO_Point := (GPIO_A'Access, 20);
   PA21   : aliased GPIO_Point := (GPIO_A'Access, 21);
   PA22   : aliased GPIO_Point := (GPIO_A'Access, 22);
   PA23   : aliased GPIO_Point := (GPIO_A'Access, 23);
   PA24   : aliased GPIO_Point := (GPIO_A'Access, 24);
   PA25   : aliased GPIO_Point := (GPIO_A'Access, 25);
   PA26   : aliased GPIO_Point := (GPIO_A'Access, 26);
   PA27   : aliased GPIO_Point := (GPIO_A'Access, 27);
   PA28   : aliased GPIO_Point := (GPIO_A'Access, 28);
   PA29   : aliased GPIO_Point := (GPIO_A'Access, 29);
   PA30   : aliased GPIO_Point := (GPIO_A'Access, 30);
   PA31   : aliased GPIO_Point := (GPIO_A'Access, 31);

   PB0    : aliased GPIO_Point := (GPIO_B'Access, 0);
   PB1    : aliased GPIO_Point := (GPIO_B'Access, 1);
   PB2    : aliased GPIO_Point := (GPIO_B'Access, 2);
   PB3    : aliased GPIO_Point := (GPIO_B'Access, 3);
   PB4    : aliased GPIO_Point := (GPIO_B'Access, 4);
   PB5    : aliased GPIO_Point := (GPIO_B'Access, 5);
   PB6    : aliased GPIO_Point := (GPIO_B'Access, 6);
   PB7    : aliased GPIO_Point := (GPIO_B'Access, 7);
   PB8    : aliased GPIO_Point := (GPIO_B'Access, 8);
   PB9    : aliased GPIO_Point := (GPIO_B'Access, 9);
   PB10   : aliased GPIO_Point := (GPIO_B'Access, 10);
   PB11   : aliased GPIO_Point := (GPIO_B'Access, 11);
   PB12   : aliased GPIO_Point := (GPIO_B'Access, 12);
   PB13   : aliased GPIO_Point := (GPIO_B'Access, 13);
   PB14   : aliased GPIO_Point := (GPIO_B'Access, 14);
   PB15   : aliased GPIO_Point := (GPIO_B'Access, 15);
   PB16   : aliased GPIO_Point := (GPIO_B'Access, 16);
   PB17   : aliased GPIO_Point := (GPIO_B'Access, 17);
   PB18   : aliased GPIO_Point := (GPIO_B'Access, 18);
   PB19   : aliased GPIO_Point := (GPIO_B'Access, 19);
   PB20   : aliased GPIO_Point := (GPIO_B'Access, 20);
   PB21   : aliased GPIO_Point := (GPIO_B'Access, 21);
   PB22   : aliased GPIO_Point := (GPIO_B'Access, 22);
   PB23   : aliased GPIO_Point := (GPIO_B'Access, 23);
   PB24   : aliased GPIO_Point := (GPIO_B'Access, 24);
   PB25   : aliased GPIO_Point := (GPIO_B'Access, 25);
   PB26   : aliased GPIO_Point := (GPIO_B'Access, 26);
   PB27   : aliased GPIO_Point := (GPIO_B'Access, 27);
   PB28   : aliased GPIO_Point := (GPIO_B'Access, 28);
   PB29   : aliased GPIO_Point := (GPIO_B'Access, 29);
   PB30   : aliased GPIO_Point := (GPIO_B'Access, 30);
   PB31   : aliased GPIO_Point := (GPIO_B'Access, 31);

   PC0    : aliased GPIO_Point := (GPIO_C'Access, 0);
   PC1    : aliased GPIO_Point := (GPIO_C'Access, 1);
   PC2    : aliased GPIO_Point := (GPIO_C'Access, 2);
   PC3    : aliased GPIO_Point := (GPIO_C'Access, 3);
   PC4    : aliased GPIO_Point := (GPIO_C'Access, 4);
   PC5    : aliased GPIO_Point := (GPIO_C'Access, 5);
   PC6    : aliased GPIO_Point := (GPIO_C'Access, 6);
   PC7    : aliased GPIO_Point := (GPIO_C'Access, 7);
   PC8    : aliased GPIO_Point := (GPIO_C'Access, 8);
   PC9    : aliased GPIO_Point := (GPIO_C'Access, 9);
   PC10   : aliased GPIO_Point := (GPIO_C'Access, 10);
   PC11   : aliased GPIO_Point := (GPIO_C'Access, 11);
   PC12   : aliased GPIO_Point := (GPIO_C'Access, 12);
   PC13   : aliased GPIO_Point := (GPIO_C'Access, 13);
   PC14   : aliased GPIO_Point := (GPIO_C'Access, 14);
   PC15   : aliased GPIO_Point := (GPIO_C'Access, 15);
   PC16   : aliased GPIO_Point := (GPIO_C'Access, 16);
   PC17   : aliased GPIO_Point := (GPIO_C'Access, 17);
   PC18   : aliased GPIO_Point := (GPIO_C'Access, 18);
   PC19   : aliased GPIO_Point := (GPIO_C'Access, 19);
   PC20   : aliased GPIO_Point := (GPIO_C'Access, 20);
   PC21   : aliased GPIO_Point := (GPIO_C'Access, 21);
   PC22   : aliased GPIO_Point := (GPIO_C'Access, 22);
   PC23   : aliased GPIO_Point := (GPIO_C'Access, 23);
   PC24   : aliased GPIO_Point := (GPIO_C'Access, 24);
   PC25   : aliased GPIO_Point := (GPIO_C'Access, 25);
   PC26   : aliased GPIO_Point := (GPIO_C'Access, 26);
   PC27   : aliased GPIO_Point := (GPIO_C'Access, 27);
   PC28   : aliased GPIO_Point := (GPIO_C'Access, 28);
   PC29   : aliased GPIO_Point := (GPIO_C'Access, 29);
   PC30   : aliased GPIO_Point := (GPIO_C'Access, 30);
   PC31   : aliased GPIO_Point := (GPIO_C'Access, 31);

   PD0    : aliased GPIO_Point := (GPIO_D'Access, 0);
   PD1    : aliased GPIO_Point := (GPIO_D'Access, 1);
   PD2    : aliased GPIO_Point := (GPIO_D'Access, 2);
   PD3    : aliased GPIO_Point := (GPIO_D'Access, 3);
   PD4    : aliased GPIO_Point := (GPIO_D'Access, 4);
   PD5    : aliased GPIO_Point := (GPIO_D'Access, 5);
   PD6    : aliased GPIO_Point := (GPIO_D'Access, 6);
   PD7    : aliased GPIO_Point := (GPIO_D'Access, 7);
   PD8    : aliased GPIO_Point := (GPIO_D'Access, 8);
   PD9    : aliased GPIO_Point := (GPIO_D'Access, 9);
   PD10   : aliased GPIO_Point := (GPIO_D'Access, 10);
   PD11   : aliased GPIO_Point := (GPIO_D'Access, 11);
   PD12   : aliased GPIO_Point := (GPIO_D'Access, 12);
   PD13   : aliased GPIO_Point := (GPIO_D'Access, 13);
   PD14   : aliased GPIO_Point := (GPIO_D'Access, 14);
   PD15   : aliased GPIO_Point := (GPIO_D'Access, 15);
   PD16   : aliased GPIO_Point := (GPIO_D'Access, 16);
   PD17   : aliased GPIO_Point := (GPIO_D'Access, 17);
   PD18   : aliased GPIO_Point := (GPIO_D'Access, 18);
   PD19   : aliased GPIO_Point := (GPIO_D'Access, 19);
   PD20   : aliased GPIO_Point := (GPIO_D'Access, 20);
   PD21   : aliased GPIO_Point := (GPIO_D'Access, 21);
   PD22   : aliased GPIO_Point := (GPIO_D'Access, 22);
   PD23   : aliased GPIO_Point := (GPIO_D'Access, 23);
   PD24   : aliased GPIO_Point := (GPIO_D'Access, 24);
   PD25   : aliased GPIO_Point := (GPIO_D'Access, 25);
   PD26   : aliased GPIO_Point := (GPIO_D'Access, 26);
   PD27   : aliased GPIO_Point := (GPIO_D'Access, 27);
   PD28   : aliased GPIO_Point := (GPIO_D'Access, 28);
   PD29   : aliased GPIO_Point := (GPIO_D'Access, 29);
   PD30   : aliased GPIO_Point := (GPIO_D'Access, 30);
   PD31   : aliased GPIO_Point := (GPIO_D'Access, 31);

   PE0    : aliased GPIO_Point := (GPIO_E'Access, 0);
   PE1    : aliased GPIO_Point := (GPIO_E'Access, 1);
   PE2    : aliased GPIO_Point := (GPIO_E'Access, 2);
   PE3    : aliased GPIO_Point := (GPIO_E'Access, 3);
   PE4    : aliased GPIO_Point := (GPIO_E'Access, 4);
   PE5    : aliased GPIO_Point := (GPIO_E'Access, 5);
   PE6    : aliased GPIO_Point := (GPIO_E'Access, 6);
   PE7    : aliased GPIO_Point := (GPIO_E'Access, 7);
   PE8    : aliased GPIO_Point := (GPIO_E'Access, 8);
   PE9    : aliased GPIO_Point := (GPIO_E'Access, 9);
   PE10   : aliased GPIO_Point := (GPIO_E'Access, 10);
   PE11   : aliased GPIO_Point := (GPIO_E'Access, 11);
   PE12   : aliased GPIO_Point := (GPIO_E'Access, 12);
   PE13   : aliased GPIO_Point := (GPIO_E'Access, 13);
   PE14   : aliased GPIO_Point := (GPIO_E'Access, 14);
   PE15   : aliased GPIO_Point := (GPIO_E'Access, 15);
   PE16   : aliased GPIO_Point := (GPIO_E'Access, 16);
   PE17   : aliased GPIO_Point := (GPIO_E'Access, 17);
   PE18   : aliased GPIO_Point := (GPIO_E'Access, 18);
   PE19   : aliased GPIO_Point := (GPIO_E'Access, 19);
   PE20   : aliased GPIO_Point := (GPIO_E'Access, 20);
   PE21   : aliased GPIO_Point := (GPIO_E'Access, 21);
   PE22   : aliased GPIO_Point := (GPIO_E'Access, 22);
   PE23   : aliased GPIO_Point := (GPIO_E'Access, 23);
   PE24   : aliased GPIO_Point := (GPIO_E'Access, 24);
   PE25   : aliased GPIO_Point := (GPIO_E'Access, 25);
   PE26   : aliased GPIO_Point := (GPIO_E'Access, 26);
   PE27   : aliased GPIO_Point := (GPIO_E'Access, 27);
   PE28   : aliased GPIO_Point := (GPIO_E'Access, 28);
   PE29   : aliased GPIO_Point := (GPIO_E'Access, 29);
   PE30   : aliased GPIO_Point := (GPIO_E'Access, 30);
   PE31   : aliased GPIO_Point := (GPIO_E'Access, 31);

   Internal_SPI_0 : aliased Internal_SPI_Port with Import, Volatile, Address => SPI0_Base;
   Internal_SPI_1 : aliased Internal_SPI_Port with Import, Volatile, Address => SPI1_Base;

   SPI_0_Cs0      : aliased SPI_Port (Internal_SPI_0'Access, 0);
   SPI_0_Cs1      : aliased SPI_Port (Internal_SPI_0'Access, 1);
   SPI_0_Cs2      : aliased SPI_Port (Internal_SPI_0'Access, 2);
   SPI_0_Cs3      : aliased SPI_Port (Internal_SPI_0'Access, 3);

   SPI_1_Cs0      : aliased SPI_Port (Internal_SPI_1'Access, 0);
   SPI_1_Cs1      : aliased SPI_Port (Internal_SPI_1'Access, 1);
   SPI_1_Cs2      : aliased SPI_Port (Internal_SPI_1'Access, 2);
   SPI_1_Cs3      : aliased SPI_Port (Internal_SPI_1'Access, 3);

end SAM.Device;
